package com.application_service.common.exceprion;

public enum ErrorCode {

    USER_NOT_FOUND,
    EMPTY_CV,
    CV_TOO_LARGE,
    IS_EMPTY,
    INVALID_CV_TYPE,
    CV_UPLOADED_FAILED,
    CV_NOT_FOUND,
    CV_DATA_INVALID,
    JOB_NOT_FOUND,
    CV_PARSING_DATA_NOT_FOUND,
    CANDIDATE_SKILL_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    EXPERIENCE_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    NO_FACE_FOUND,
    VALIDATION_ERROR,
    NOT_VALID_OPERATION,
    SALARY_NOT_VALID,

    EDUCATION_NOT_FOUND,
    CANDIDATE_NOT_AVAILABLE,
    CANDIDATE_NOT_FOUND,
    SKILL_NOT_FOUND,
    ACCESS_DENIED;


}