package com.Candidate_Service.common.exceprion;

public enum ErrorCode {

    USER_NOT_FOUND,

    JOB_NOT_FOUND,
    CANDIDATE_SKILL_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    EXPERIENCE_NOT_FOUND,
    INTERNAL_SERVER_ERROR,

    VALIDATION_ERROR,

    SALARY_NOT_VALID,

    EDUCATION_NOT_FOUND,
    CANDIDATE_NOT_AVAILABLE,
    CANDIDATE_NOT_FOUND,
    SKILL_NOT_FOUND,
    ACCESS_DENIED;


}